[features]
seeds = false
skip-lint = false
[programs.devnet]
cat_gif_contract = "FjwoJ35JBcJJXB5dVfY2EjU2fNXZSgVi1whNXWadFzsi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/windss/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
